// Reader for the knockout (R32) forecast-performance metrics — the 淘汰赛 tab of
// the 预测效果 / track-record page. Generated by scripts/world-cup/fifa8-performance.ts
// from the FIFA 8-model forecasts, settled results, and prediction-time Polymarket
// prices (post-hoc benchmark only; the forecasts stay market-blind). The per-match
// table + calibration bins score the published (multi-calibrated) forecaster, so
// the page shape matches the group-stage tab exactly. Statically imported — SSG.

import fifa8PerfData from "./generated/fifa8-performance.generated.json";
import type { PerfAgg, PerfBin, PerfMatch, Performance } from "./performance";

interface Fifa8ForecasterPerf {
  readonly id: string;
  readonly name: string;
  readonly family: string;
  readonly agg: PerfAgg;
}

interface Fifa8Performance {
  readonly generatedAt: string;
  readonly headline: string;
  readonly settled: number;
  readonly forecasters: readonly Fifa8ForecasterPerf[];
  readonly matches: readonly PerfMatch[];
  readonly bins: readonly PerfBin[];
}

const DATA = fifa8PerfData as unknown as Fifa8Performance;

// The knockout tab surfaces the published (multi-calibrated) forecaster's numbers
// in the same {agg, matches, bins} shape the group-stage tab renders.
export function getKnockoutPerformance(): Performance {
  const headline = DATA.forecasters.find((f) => f.id === DATA.headline) ?? DATA.forecasters[0];
  if (!headline) {
    throw new Error("fifa8-performance.generated.json has no forecasters — rerun scripts/world-cup/fifa8-performance.ts");
  }
  return {
    generatedAt: DATA.generatedAt,
    agg: headline.agg,
    matches: DATA.matches,
    bins: DATA.bins
  };
}
