import predictionsData from "./generated/predictions.generated.json";
import contentTwData from "./generated/content-zh-TW.generated.json";
import resultsData from "./generated/results.generated.json";
import type { Locale } from "./i18n";

// Market-blind forecast store. Data is generated by
// scripts/world-cup/import-predictions.ts from the harness archives and
// statically imported — SSG, no runtime fs, no backend, and by policy it
// contains no market prices anywhere.

export type ForecastFamily =
  | "group_match"
  | "group_winner"
  | "reach_quarterfinal"
  | "reach_semifinal"
  | "champion";

export interface ForecastOutcome {
  readonly key: string;
  readonly label_cn: string;
  readonly label_en: string;
  readonly p: number;
}

export interface ForecastReason {
  readonly cn: string;
  readonly en: string;
  readonly source_url: string;
  readonly source_date: string;
}

export interface Forecast {
  readonly id: string;
  readonly family: ForecastFamily;
  readonly event_slug: string;
  readonly question_cn: string;
  readonly question_en: string;
  readonly kickoff_utc: string | null;
  readonly generated_at: string;
  readonly outcomes: readonly ForecastOutcome[];
  readonly one_liner_cn: string;
  readonly one_liner_en: string;
  readonly key_reasons: readonly ForecastReason[];
  readonly confidence_tier: string;
  readonly n_sources: number;
  readonly method_note: string;
  readonly dir: string;
}

interface GeneratedFile {
  readonly generatedAt: string;
  readonly counts: Record<string, number>;
  readonly total: number;
  readonly entries: readonly Forecast[];
}

const data = predictionsData as unknown as GeneratedFile;

export function getAllForecasts(): readonly Forecast[] {
  return data.entries;
}

export function getGeneratedAt(): string {
  // Latest forecast generation time (not the import/build time).
  return data.entries.reduce((m, e) => (e.generated_at > m ? e.generated_at : m), "");
}

export function getForecastByDir(dir: string): Forecast | null {
  return data.entries.find((e) => e.dir === dir) ?? null;
}

export function getByFamily(family: ForecastFamily): readonly Forecast[] {
  return data.entries.filter((e) => e.family === family);
}

interface ContentTranslation {
  question: string;
  one_liner: string;
  reasons: string[];
}

const CONTENT_TW = (contentTwData as unknown as { content: Record<string, ContentTranslation> }).content ?? {};

// Localized card content: en/zh-CN straight from the bilingual data; zh-TW from
// the opencc-generated Traditional pack, falling back to Simplified if absent.
export function contentFor(
  f: Forecast,
  locale: Locale
): { question: string; oneLiner: string; reasons: readonly string[] } {
  if (locale === "en") {
    return { question: f.question_en, oneLiner: f.one_liner_en, reasons: f.key_reasons.map((r) => r.en) };
  }
  if (locale === "zh-TW") {
    const tw = CONTENT_TW[f.id];
    if (tw && tw.one_liner) {
      return {
        question: tw.question || f.question_cn,
        oneLiner: tw.one_liner,
        reasons: f.key_reasons.map((r, i) => tw.reasons[i] ?? r.cn)
      };
    }
  }
  return { question: f.question_cn, oneLiner: f.one_liner_cn, reasons: f.key_reasons.map((r) => r.cn) };
}

export function sortedOutcomes(f: Forecast): readonly ForecastOutcome[] {
  return [...f.outcomes].sort((a, b) => b.p - a.p);
}

// Settled group-stage result, recovered from Polymarket settlement mapping
// (winner + final score only — market-blind, no prices). Generated by
// scripts/world-cup/update-results.ts into results.generated.json.
export interface MatchResult {
  readonly event_slug: string;
  readonly status: "resolved" | "pending";
  readonly winner: "a" | "draw" | "b" | null;
  readonly homeGoals: number | null;
  readonly awayGoals: number | null;
  readonly score: string | null;
  readonly settledAt: string | null;
  readonly source: "exact_score" | "moneyline" | null;
}

const RESULTS = (resultsData as unknown as { results: Record<string, MatchResult> }).results ?? {};

// The model's single best pick for a fixture: the highest-probability outcome.
export function bestPickKey(f: Forecast): "a" | "draw" | "b" {
  const byKey = Object.fromEntries(f.outcomes.map((o) => [o.key, o.p]));
  const pA = byKey.a ?? 0;
  const pD = byKey.draw ?? 0;
  const pB = byKey.b ?? 0;
  const top = Math.max(pA, pD, pB);
  return top === pA ? "a" : top === pB ? "b" : "draw";
}

// Resolved result for a fixture, or null if it hasn't settled yet.
export function getResult(eventSlug: string): MatchResult | null {
  const r = RESULTS[eventSlug];
  return r && r.status === "resolved" ? r : null;
}

// How many group-stage fixtures have settled so far.
export function resolvedCount(): number {
  return Object.values(RESULTS).filter((r) => r.status === "resolved").length;
}

// Group-stage matches keyed by calendar date (from the event slug), ascending.
export function matchesByDate(): ReadonlyArray<{ date: string; matches: readonly Forecast[] }> {
  const matches = getByFamily("group_match");
  const byDate = matches.reduce((acc, m) => {
    const date = m.event_slug.match(/(\d{4}-\d{2}-\d{2})/)?.[1] ?? "未定";
    const existing = acc.get(date) ?? [];
    return new Map(acc).set(date, [...existing, m]);
  }, new Map<string, Forecast[]>());
  return [...byDate.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([date, ms]) => ({
      date,
      matches: [...ms].sort((a, b) => (a.kickoff_utc ?? "").localeCompare(b.kickoff_utc ?? ""))
    }));
}
