// UI strings for the multilingual site (zh / en / ja / es). zh+en live here;
// ja+es come from locales.generated.json (agent-translated) with English
// fallback. Forecast content (questions, one-liners, reasons) is bilingual in
// the data layer; ja/es content lives in translations.generated.json. Lang
// travels as the ?lang= query param (zh = no param).

import localesData from "./generated/locales.generated.json";

export type Lang = "zh" | "en" | "ja" | "es";

export const LANGS: ReadonlyArray<{ code: Lang; label: string }> = [
  { code: "zh", label: "中文" },
  { code: "en", label: "English" },
  { code: "ja", label: "日本語" },
  { code: "es", label: "Español" }
];

interface LocalePack {
  ui: Record<string, string>;
  teams: Record<string, string>;
  steps: Array<{ n: string; title: string; copy: string; tag: string }>;
  pe: Record<string, string>;
}

const LOCALES = localesData as unknown as Record<"ja" | "es", LocalePack>;

export function langOf(param: string | undefined): Lang {
  return param === "en" || param === "ja" || param === "es" ? param : "zh";
}

export function withLang(href: string, lang: Lang): string {
  if (lang === "zh") return href;
  return href.includes("?") ? `${href}&lang=${lang}` : `${href}?lang=${lang}`;
}

export const STR = {
  navForecasts: { zh: "预测", en: "Forecasts" },
  navBracket: { zh: "对阵", en: "Bracket" },
  navDeploy: { zh: "本地部署", en: "Self-host" },
  edition: { zh: "世界杯版", en: "World Cup" },
  heroTitle: { zh: "世界杯", en: "World Cup" },
  tabChampion: { zh: "冠军", en: "Champion" },
  tabGroups: { zh: "小组赛", en: "Groups" },
  tabKnockout: { zh: "出线名单", en: "Knockouts" },
  heroMeta: {
    zh: "87 个问题公开预测 · 不读取任何市场价格 · Brier 公开记分 · 预测时间",
    en: "87 public forecasts · no market prices consulted · publicly Brier-scored · forecast time"
  },
  subChampion: {
    zh: "谁会捧起 2026 年 7 月 19 日的大力神杯？48 支球队的夺冠概率由我们的 forecasting agent 独立生成：以 Elo 实力评级为先验，跑 10 万次蒙特卡洛锦标赛模拟，再用伤停、阵容、状态等关键信息做贝叶斯更新——全程不参考任何市场价格。",
    en: "Who lifts the trophy on July 19, 2026? Title probabilities for all 48 teams, generated by our forecasting agent: an Elo prior run through 100,000 Monte-Carlo tournament simulations, then Bayesian-updated with key evidence — injuries, squads, form — without ever consulting a market price."
  },
  subGroups: {
    zh: "72 场小组赛逐场预测：每一场给出胜 / 平 / 负三路概率与模型判断。点开任意一场看主要理由与完整推理。",
    en: "All 72 group-stage matches: win / draw / loss probabilities and the model's pick for every fixture. Open any match for the key reasons and full reasoning."
  },
  subKnockout: {
    zh: "从小组出线到决赛的完整对阵推演：淘汰赛每个节点取最可能的结果并旁标该场胜率，连线一路通向决赛。",
    en: "The complete run from group qualification to the final: every knockout node takes the most likely result with its per-tie win probability, lines running all the way to the final."
  },
  ruleNote: {
    zh: "规则：每组前两名直接晋级 32 强；12 个小组的第三名中，成绩最好的 8 支同样晋级——所以每个组会有 2 支或 3 支球队出线。",
    en: "Format: the top two in every group advance to the round of 32, joined by the 8 best third-placed teams across the 12 groups — so each group sends 2 or 3 teams through."
  },
  groupsCol: { zh: "小组出线 · 含出线概率", en: "Group qualification · advance %" },
  r32: { zh: "32 强", en: "Round of 32" },
  r16: { zh: "16 强", en: "Round of 16" },
  qf: { zh: "八强", en: "Quarterfinals" },
  sf: { zh: "四强", en: "Semifinals" },
  finalCol: { zh: "决赛 · 7 月 19 日", en: "Final · July 19" },
  out: { zh: "出局", en: "OUT" },
  predictedChampion: { zh: "预测冠军", en: "Predicted champion" },
  finalWinProb: { zh: "决赛胜率", en: "Final win prob" },
  marginalTitle: {
    zh: "边际概率（每队独立计算，与上方单一剧本互补）",
    en: "Marginal probabilities (per team, complementary to the single bracket path above)"
  },
  qfBoard: { zh: "八强概率榜", en: "Quarterfinal probabilities" },
  sfBoard: { zh: "四强概率榜", en: "Semifinal probabilities" },
  sumQf: { zh: "48 队概率之和 ≈ 8", en: "48 teams sum ≈ 8" },
  sumSf: { zh: "48 队概率之和 ≈ 4", en: "48 teams sum ≈ 4" },
  ourTake: { zh: "我们的观点", en: "Our take" },
  fullReasoning: { zh: "查看完整推理 →", en: "Read the full reasoning →" },
  fullReport: { zh: "完整推理报告 →", en: "Full reasoning report →" },
  sources: { zh: "个来源", en: "sources" },
  confidence: { zh: "置信", en: "confidence" },
  source: { zh: "来源", en: "source" },
  cloudNote: {
    zh: "旗帜大小 ∝ 夺冠概率 · 点击查看完整推理",
    en: "Flag size ∝ title probability · click for full reasoning"
  },
  winnerPick: { zh: "头名预测", en: "Winner pick" },
  group: { zh: "组", en: "Group" },
  draw: { zh: "平局", en: "Draw" },
  drawShort: { zh: "平", en: "D" },
  winSuffix: { zh: "胜", en: "" },
  importing: { zh: "预测数据导入中。", en: "Forecast data is being imported." },
  qualified: { zh: "晋级", en: "IN" },
  tierHigh: { zh: "高", en: "high" },
  tierMedium: { zh: "中", en: "medium" },
  tierLow: { zh: "低", en: "low" },
  langLabel: { zh: "语言", en: "Language" },
  sampleTitle: { zh: "示例运行", en: "Sample run" },
  sampleHint: { zh: "选择一个真实问题，看 agent 当时的完整输出", en: "Pick a real question to see the agent's actual output" },
  formulaTitle: { zh: "统计基线公式", en: "Baseline formulas" },
  formulaLegend: {
    zh: "ν = 0.7（平局参数）· R 为实时 Elo 评级 · Δ 为证据驱动的有界修正（单场 |Δ| ≤ 8pp，更新后归一化）",
    en: "ν = 0.7 (draw parameter) · R is the live Elo rating · Δ is the evidence-driven bounded shift (|Δ| ≤ 8pp per match, renormalized)"
  },
  workbench: { zh: "工作台", en: "Workbench" },
  wbReady: { zh: "已就绪", en: "Ready" },
  wbSoon: {
    zh: "完整工作台即将开放——先在下方试试示例运行。",
    en: "The full workbench is coming soon — try the sample run below."
  },
  reportFallback: {
    zh: "完整报告以中文/英文存档。",
    en: "Full report available in English below; card content is localized."
  },
  finalTag: { zh: "完场", en: "FT" },
  pickHit: { zh: "预测命中", en: "Pick hit" },
  pickMiss: { zh: "预测未中", en: "Pick missed" }
} as const;

export type StrKey = keyof typeof STR;

export function t(lang: Lang, key: StrKey): string {
  if (lang === "zh" || lang === "en") return STR[key][lang];
  return LOCALES[lang]?.ui?.[key] ?? STR[key].en;
}

export function teamLabel(meta: { cn: string; en: string }, lang: Lang): string {
  if (lang === "zh") return meta.cn;
  if (lang === "en") return meta.en;
  return LOCALES[lang]?.teams?.[meta.en] ?? meta.en;
}

const TIER_KEY: Record<string, StrKey> = { 高: "tierHigh", 中: "tierMedium", 低: "tierLow" };

export function tierLabel(lang: Lang, tier: string): string {
  const key = TIER_KEY[tier];
  return key ? t(lang, key) : tier;
}

export function localeSteps(lang: Lang): Array<{ n: string; title: string; copy: string; tag: string }> | null {
  if (lang === "ja" || lang === "es") {
    const steps = LOCALES[lang]?.steps;
    return steps && steps.length > 0 ? steps : null;
  }
  return null;
}

export function localePe(lang: Lang): Record<string, string> {
  if (lang === "ja" || lang === "es") return LOCALES[lang]?.pe ?? {};
  return {};
}
