// Reader for the forecast-performance metrics (the 预测效果 / track-record page).
// Generated by scripts/world-cup/build-performance.ts from the forecasts, settled
// results, and captured prediction-time Polymarket prices. Statically imported —
// SSG, no runtime fetch. Forecasts stay market-blind; this only benchmarks them
// after the fact, and surfaces percentages only (no money).

import perfData from "./generated/performance.generated.json";

export type LegKey = "a" | "draw" | "b";
export type Side = "yes" | "no" | "skip";

export interface PerfLeg {
  readonly leg: LegKey;
  readonly side: Side;
  readonly retPct: number | null;
  readonly win: boolean;
}
export interface PerfMatch {
  readonly slug: string;
  readonly homeEn: string;
  readonly awayEn: string;
  readonly score: string | null;
  readonly winner: LegKey;
  readonly our: readonly [number, number, number];
  readonly mkt: readonly [number, number, number];
  readonly legs: readonly PerfLeg[];
}
export interface PerfBin {
  readonly lo: number;
  readonly hi: number;
  readonly n: number;
  readonly predPct: number;
  readonly obsPct: number;
}
export interface PerfAgg {
  readonly settled: number;
  readonly bestPickHit: number;
  readonly bestPickPct: number;
  readonly roiPct: number;
  readonly bets: number;
  readonly wins: number;
  readonly skips: number;
  readonly bssPct: number;
  readonly ecePct: number;
}
export interface Performance {
  readonly generatedAt: string;
  readonly agg: PerfAgg;
  readonly matches: readonly PerfMatch[];
  readonly bins: readonly PerfBin[];
}

const PERF = perfData as unknown as Performance;

export function getPerformance(): Performance {
  return PERF;
}
