// Demo run for the Market Impact Engine: Zhipu AI’s GLM-4 "G2M 5.2" open-weight
// release and its read-through to NVDA and GOOGL across three horizons.
//
// Generated by a multi-agent forecasting pipeline (web-grounded research +
// adversarial calibration), then passed through a concision/voice edit so each
// call is one tight, decision-first line with the depth kept in the evidence
// pool. Illustrative scenario analysis anchored in real precedents (e.g. the
// Jan-2025 DeepSeek reaction) — NOT financial advice.

import type { MarketImpactRun } from "./types";

export const GLM4_DEMO: MarketImpactRun = {
  "id": "glm4-nvda-googl",
  "eventDate": "2026-06-17",
  "event_en": "Chinese lab Zhipu AI (\"智谱\") releases a new flagship open-weight model in its GLM-4 line (\"G2M 5.2\"), claiming frontier-level reasoning at a large training/inference cost reduction, with open weights.",
  "event_zh": "中国实验室智谱 AI 在其 GLM-4 系列中发布新旗舰开源模型（\"G2M 5.2\"），宣称以大幅降低的训练/推理成本达到前沿级推理能力，并开放权重。",
  "summary_en": "A sentiment ripple, not a DeepSeek repeat. NVDA: maybe a knee-jerk dip today, flat for 3 months, a modest 1-year tailwind as reasoning eats inference compute — the real risk is custom ASICs, not this model. GOOGL: smaller still — it sells AI and owns cheap TPUs, so cheaper models mostly help; short-term is a coin-flip, the 2026 tape is desensitized to Chinese launches.",
  "summary_zh": "这是情绪涟漪，不是 DeepSeek 重演。NVDA：今天可能膝跳式下跌，三个月走平，一年以上温和利好——推理吃掉更多算力；真正的风险是自研 ASIC，不是这款模型。GOOGL：影响更小——它卖 AI、又自研廉价 TPU，模型变便宜多半帮它；短期接近抛硬币，2026 的市场对中国发布已脱敏。",
  "disclaimer_en": "Illustrative scenario analysis for a consumer research demo — NOT financial, investment, or trading advice. \"G2M 5.2\" is a hypothetical scenario; magnitudes and mechanisms are anchored to real, cited precedents (the Jan-2025 DeepSeek shock, hyperscaler capex, export controls, custom ASICs, the Jevons-paradox debate) but are not predictions of actual prices. Markets are uncertain and can move against any thesis here. Do your own research and consult a licensed advisor before making investment decisions.",
  "disclaimer_zh": "本内容为面向消费者研究演示的情景分析——并非财务、投资或交易建议。\"G2M 5.2\"为假设情景；其幅度与机制锚定于真实且有出处的先例（2025 年 1 月 DeepSeek 冲击、超大规模资本开支、出口管制、自研 ASIC、杰文斯悖论之争），但并非对真实价格的预测。市场存在不确定性，可能与此处任何论点相悖。投资决策前请自行研究并咨询持牌顾问。",
  "stages": [
    {
      "id": "s1",
      "title_en": "Intake & framing",
      "title_zh": "接收与定调",
      "summary_en": "Logged the event; picked the two most exposed names — NVDA (sells compute) and GOOGL (model + distribution).",
      "summary_zh": "记录事件；选出两只最受影响标的——NVDA（卖算力）与 GOOGL（模型+分发）。"
    },
    {
      "id": "s2",
      "title_en": "Mechanism mapping",
      "title_zh": "机制映射",
      "summary_en": "Mapped the bear path (cheaper model → less GPU capex) against the bull path (Jevons; TPU + distribution moats).",
      "summary_zh": "梳理利空路径（便宜模型→少买 GPU）与利多路径（杰文斯；TPU+分发护城河）。"
    },
    {
      "id": "s3",
      "title_en": "Evidence assembly",
      "title_zh": "证据汇总",
      "summary_en": "Pulled 15 dated precedents into one pool: DeepSeek’s crash, Nadella’s Jevons, Huang’s 100x, $700B capex, ASICs.",
      "summary_zh": "汇入 15 条带日期先例：DeepSeek 暴跌、纳德拉杰文斯、黄仁勋 100 倍、7000 亿资本开支、ASIC。"
    },
    {
      "id": "s4",
      "title_en": "Per-horizon scenarios",
      "title_zh": "分时段情景",
      "summary_en": "Built today / 3-month / 1-year cases per ticker — direction, magnitude band, and the swing factors to watch.",
      "summary_zh": "为每只标的建 今天/3 月/1 年 情景：方向、幅度区间、需盯的摆动因素。"
    },
    {
      "id": "s5",
      "title_en": "Adversarial cross-check",
      "title_zh": "对抗式交叉核对",
      "summary_en": "Red-teamed it: the DeepSeek recovery took ~6 months (not weeks); added the bubble overhang and ASIC substitution; trimmed confidence.",
      "summary_zh": "红队复核：DeepSeek 修复约 6 个月（非几周）；补入泡沫隐忧与 ASIC 替代；下调置信度。"
    },
    {
      "id": "s6",
      "title_en": "Verdict & calibration",
      "title_zh": "结论与校准",
      "summary_en": "Final read at trimmed confidence: NVDA wobble / neutral / up; GOOGL coin-flip / neutral / up.",
      "summary_zh": "下调置信度后定论：NVDA 震荡/中性/上行；GOOGL 抛硬币/中性/上行。"
    }
  ],
  "evidence": [
    {
      "id": "ev1",
      "sourceType": "news",
      "title_en": "Nvidia loses $589B in market cap amid DeepSeek AI impact (NVDA -17%, biggest one-day loss ever)",
      "title_zh": "DeepSeek 冲击下英伟达市值蒸发 5890 亿美元（NVDA -17%，史上最大单日损失）",
      "date": "2025-01-27",
      "stance": "oppose",
      "weightPct": 15,
      "reliability": 0.9,
      "excerpt_en": "On Jan 27, 2025 NVDA fell ~17% (from ~$142 to ~$118.50) and shed $589B in market cap, the largest single-day loss in history, on fears a cheaper Chinese model would cut GPU demand — the core bear template for this scenario.",
      "excerpt_zh": "2025 年 1 月 27 日 NVDA 下跌约 17%（从约 142 美元至约 118.50 美元）、蒸发 5890 亿美元市值，为史上最大单日损失，源于担忧更便宜的中国模型削减 GPU 需求——本情景的核心利空模板。",
      "url": "https://www.cnbc.com/2025/01/27/nvidia-sheds-almost-600-billion-in-market-cap-biggest-drop-ever.html"
    },
    {
      "id": "ev2",
      "sourceType": "news",
      "title_en": "Satya Nadella: 'Jevons paradox strikes again' — cheaper AI makes usage skyrocket",
      "title_zh": "纳德拉：'杰文斯悖论再次显现'——更便宜的 AI 让用量暴增",
      "date": "2025-01-27",
      "stance": "support",
      "weightPct": 12,
      "reliability": 0.85,
      "excerpt_en": "Microsoft's CEO argued cheaper, more efficient AI makes usage 'skyrocket,' turning compute into a commodity demanded in ever-greater volume — the central bull rebuttal to the cheap-model bear case for both NVDA and GOOGL.",
      "excerpt_zh": "微软 CEO 认为更便宜、更高效的 AI 会让用量'暴增'，把算力变成需求越来越大的商品——这是对 NVDA 与 GOOGL'便宜模型'利空论的核心多头反驳。",
      "url": "https://fortune.com/2025/01/27/microsoft-ceo-satya-nadella-deepseek-optimism-jevons-paradox/"
    },
    {
      "id": "ev3",
      "sourceType": "news",
      "title_en": "Jensen Huang: reasoning AI (he praised DeepSeek R1 as 'world class') needs ~100x more compute",
      "title_zh": "黄仁勋：推理 AI（他赞 DeepSeek R1'世界级'）所需算力约为 100 倍",
      "date": "2025-02-27",
      "stance": "support",
      "weightPct": 11,
      "reliability": 0.85,
      "excerpt_en": "Huang said reasoning models run queries many times over, requiring ~100x the compute of a one-shot answer, and called DeepSeek R1 'absolutely world class' — directly bullish for inference-GPU demand and the long-horizon NVDA thesis.",
      "excerpt_zh": "黄仁勋称推理模型会多次运行查询，所需算力约为单次回答的 100 倍，并称 DeepSeek R1'绝对世界级'——对推理 GPU 需求及 NVDA 长期论点构成直接利多。",
      "url": "https://www.cnbc.com/2025/03/19/nvidia-ceo-jensen-huang-why-deepseek-model-needs-100-times-more-computing.html"
    },
    {
      "id": "ev4",
      "sourceType": "analyst",
      "title_en": "Hyperscalers' 2026 AI spending plans top $700 billion (~$450B AI-specific)",
      "title_zh": "超大规模厂商 2026 年 AI 支出计划突破 7000 亿美元（约 4500 亿与 AI 直接相关）",
      "date": "2026-02-15",
      "stance": "support",
      "weightPct": 9,
      "reliability": 0.8,
      "excerpt_en": "2026 hyperscaler capex is tracking $700B+ with Amazon ~$200B, Alphabet $175-185B, Meta $125-145B and Microsoft ~$120B+ — the structural demand floor under NVDA that historically reasserts itself within weeks-to-months.",
      "excerpt_zh": "2026 年超大规模资本开支正奔向 7000 亿美元以上，亚马逊约 2000 亿、Alphabet 1750-1850 亿、Meta 1250-1450 亿、微软约 1200 亿+——构成 NVDA 的结构性需求底，历史上数周至数月内即重新占上风。",
      "url": "https://finance.yahoo.com/sectors/technology/articles/hyperscalers-hit-700-billion-2026-111243744.html"
    },
    {
      "id": "ev5",
      "sourceType": "filing",
      "title_en": "NVDA FY26 Q1: $4.5B H20 charge, ~$8B lost China revenue (export controls)",
      "title_zh": "NVDA 26 财年一季度：H20 减记 45 亿美元，损失约 80 亿美元中国收入（出口管制）",
      "date": "2025-05-28",
      "stance": "mixed",
      "weightPct": 7,
      "reliability": 0.95,
      "excerpt_en": "US export controls forced a $4.5B H20 inventory charge and ~$8B of lost Q2 China revenue (later partly resumed via 15-25% revenue-share deals) — the real, durable structural risk for NVDA versus a single model release.",
      "excerpt_zh": "美国出口管制迫使 NVDA 计提 45 亿美元 H20 库存减记、损失约 80 亿美元二季度中国收入（后通过 15-25% 收入分成协议部分恢复）——相较单次模型发布，这才是 NVDA 真实且持久的结构性风险。",
      "url": "https://www.sec.gov/Archives/edgar/data/0001045810/000104581025000115/q1fy26cfocommentary.htm"
    },
    {
      "id": "ev6",
      "sourceType": "market-data",
      "title_en": "Nvidia's ~6-month round trip: sub-$100 in April 2025, fresh record ~$173 only in July 2025",
      "title_zh": "英伟达约 6 个月往返：2025 年 4 月跌破 100 美元，直到 7 月才以约 173 美元创新高",
      "date": "2025-07-17",
      "stance": "oppose",
      "weightPct": 8,
      "reliability": 0.85,
      "excerpt_en": "After DeepSeek, NVDA fell below $100 by April 2025 and did not reclaim a new all-time high (~$173, first $4T market cap) until July 17, 2025 — a ~6-month recovery driven by H20 export relief and Saudi/UAE sovereign chip deals, not a 'weeks-long' mechanical bounce. Corrects the mid-horizon 'V-shape in weeks' overstatement.",
      "excerpt_zh": "DeepSeek 之后，NVDA 到 2025 年 4 月跌破 100 美元，直到 7 月 17 日才以约 173 美元（首家 4 万亿市值）创新高——这是约 6 个月、靠 H20 出口解禁与沙特/阿联酋主权芯片订单驱动的修复，而非'几周'机械反弹。纠正了中期'几周 V 形'的夸大。",
      "url": "https://www.aol.com/nvidia-stock-jumps-highest-levels-183528286.html"
    },
    {
      "id": "ev7",
      "sourceType": "news",
      "title_en": "OpenAI misses revenue/user targets, triggering an AI-infrastructure selloff (Oracle -7% premarket)",
      "title_zh": "OpenAI 收入/用户目标双双不及预期，引发 AI 基建抛售（甲骨文盘前 -7%）",
      "date": "2026-04-28",
      "stance": "oppose",
      "weightPct": 6,
      "reliability": 0.85,
      "excerpt_en": "On 2026-04-28 a report that OpenAI missed revenue/user targets sent Oracle -7% premarket and CoreWeave/SoftBank sharply lower — evidence the 2026 tape is twitchy on demand-side doubt, a fresh circular-financing overhang that fattens the short/mid-horizon left tail for NVDA.",
      "excerpt_zh": "2026 年 4 月 28 日，OpenAI 收入/用户不及目标的报道令甲骨文盘前 -7%、CoreWeave 与软银大跌——表明 2026 年盘面对需求端疑虑敏感，这是加厚 NVDA 短/中期左尾的新循环融资隐忧。",
      "url": "https://www.cnbc.com/2026/04/28/openai-reportedly-missed-revenue-targets-shares-of-oracle-and-these-chip-stocks-are-falling.html"
    },
    {
      "id": "ev8",
      "sourceType": "analyst",
      "title_en": "Custom AI ASIC state of play: Broadcom ~70% share; Google/Meta/Anthropic multi-year deals; TPUs ~30-40% cheaper on inference",
      "title_zh": "自研 AI ASIC 现状：博通约 70% 份额；谷歌/Meta/Anthropic 多年合约；TPU 推理成本低约 30-40%",
      "date": "2026-05-01",
      "stance": "oppose",
      "weightPct": 7,
      "reliability": 0.8,
      "excerpt_en": "By mid-2026 Broadcom holds ~70% of the custom-accelerator market with Google TPU, Meta MTIA (extended to 2029) and Anthropic commitments; TPUs cited at 30-40% lower inference cost — directly attacking the long-horizon bull claim that cheaper inference expands NVDA's buyer base, since marginal inference dollars increasingly flow to ASICs.",
      "excerpt_zh": "到 2026 年中，博通占据约 70% 自研加速器市场，拥有谷歌 TPU、Meta MTIA（延至 2029 年）和 Anthropic 承诺；TPU 推理成本低 30-40%——直接攻击长期多头'更便宜推理扩大 NVDA 买方基础'的论点，因为边际推理支出正越来越多流向 ASIC。",
      "url": "https://www.tomshardware.com/tech-industry/semiconductors/custom-ai-asics-examined-from-broadcom-to-mtia"
    },
    {
      "id": "ev9",
      "sourceType": "market-data",
      "title_en": "DeepSeek V4 launches to 'muted' market response; analysts say 'don't expect another DeepSeek moment'",
      "title_zh": "DeepSeek V4 发布市场反应'平淡'；分析师称'别指望再现 DeepSeek 时刻'",
      "date": "2026-04-24",
      "stance": "support",
      "weightPct": 7,
      "reliability": 0.85,
      "excerpt_en": "The most recent comparable Chinese open-model launch (DeepSeek V4) drew an explicitly muted market reaction because follow-ups don't shock like the original R1 surprise — direct counter to a short-horizon knee-jerk DOWN premise for both NVDA and GOOGL.",
      "excerpt_zh": "最近一次可比的中国开源模型发布（DeepSeek V4）市场反应明确平淡，因为后续迭代不再像 R1 那次意外那样冲击市场——直接反驳 NVDA 与 GOOGL 短期'条件反射式下跌'的前提。",
      "url": "https://www.morningstar.com/markets/deepseek-v4-is-here-dont-expect-another-deepseek-moment"
    },
    {
      "id": "ev10",
      "sourceType": "news",
      "title_en": "Zhipu's GLM-5.1 first open-weight model to top Gemini 3.1 Pro on SWE-Bench Pro — shipped with no GOOGL shock",
      "title_zh": "智谱 GLM-5.1 成首个在 SWE-Bench Pro 超越 Gemini 3.1 Pro 的开源模型——发布时 GOOGL 无冲击",
      "date": "2026-04-07",
      "stance": "support",
      "weightPct": 5,
      "reliability": 0.7,
      "excerpt_en": "Zhipu already shipped a frontier open model beating Gemini 3.1 Pro on a key coding benchmark two months before the scenario date, with no documented GOOGL selloff — undercutting the claim that G2M/GLM-5.2 will produce even a modest short-horizon dip.",
      "excerpt_zh": "智谱在情景日期前两个月已发布一款在关键编码基准上击败 Gemini 3.1 Pro 的前沿开源模型，且未见 GOOGL 抛售——削弱'G2M/GLM-5.2 会引发哪怕温和短期下跌'的判断。",
      "url": "https://medium.com/@tatsuru.okada/the-first-open-weight-model-to-beat-gpt-5-4-290d269b0d3c"
    },
    {
      "id": "ev11",
      "sourceType": "news",
      "title_en": "Alphabet resets the bar for AI infrastructure spending ($180-190B 2026 capex; Gemini scale; TPUs)",
      "title_zh": "Alphabet 重设 AI 基础设施开支标杆（2026 年资本开支 1800-1900 亿；Gemini 规模；TPU）",
      "date": "2026-02-04",
      "stance": "support",
      "weightPct": 5,
      "reliability": 0.9,
      "excerpt_en": "Alphabet's record 2026 capex guidance and TPU-powered Gemini scale show the distribution-plus-vertical-integration depth that a single open Chinese model does not threaten — the core GOOGL bull anchor.",
      "excerpt_zh": "Alphabet 创纪录的 2026 年资本开支指引和由 TPU 驱动的 Gemini 规模，体现了单一开源中国模型无法撼动的'分发+垂直整合'纵深——GOOGL 多头的核心锚点。",
      "url": "https://www.cnbc.com/2026/02/04/alphabet-resets-the-bar-for-ai-infrastructure-spending.html"
    },
    {
      "id": "ev12",
      "sourceType": "fundamental",
      "title_en": "Alphabet prices $84.75B equity raise (incl. $10B Berkshire) for AI infra — capex now outruns internal cash",
      "title_zh": "Alphabet 完成 847.5 亿美元股权融资（含伯克希尔 100 亿）投入 AI 基建——资本开支已超内生现金",
      "date": "2026-06-02",
      "stance": "mixed",
      "weightPct": 4,
      "reliability": 0.95,
      "excerpt_en": "Alphabet's record external capital raise both validates the bull 'compute demand is real' case AND sharpens the bear capex-justification/circular-financing scrutiny under-weighted at the mid horizon.",
      "excerpt_zh": "Alphabet 创纪录的外部融资既验证了多头'算力需求真实'的论点，也强化了中期被低估的空头'资本开支合理性/循环融资'质疑。",
      "url": "https://www.sec.gov/Archives/edgar/data/0001652044/000119312526252362/d152107d424b5.htm"
    },
    {
      "id": "ev13",
      "sourceType": "news",
      "title_en": "Hyperscaler capex >$600B in 2026 (+36% YoY); AI depreciation exceeds combined profits; $100B AI bonds",
      "title_zh": "2026 超大规模厂商资本开支超 6000 亿（同比 +36%）；AI 折旧超过合计利润；发行 1000 亿 AI 债券",
      "date": "2025-12-22",
      "stance": "oppose",
      "weightPct": 4,
      "reliability": 0.8,
      "excerpt_en": "The capex-bubble/circular-financing/depreciation narrative is far more concrete in 2026 than the base forecasts acknowledged, making any cheaper-frontier-model headline a sharper catalyst for the 'is the spend justified?' debate across NVDA and GOOGL.",
      "excerpt_zh": "资本开支泡沫/循环融资/折旧叙事在 2026 年远比基础预测所承认的更具体，使任何'更便宜前沿模型'的标题更易成为针对 NVDA 与 GOOGL'开支值不值'争论的催化剂。",
      "url": "https://techblog.comsoc.org/2025/12/22/hyperscaler-capex-600-bn-in-2026-a-36-increase-over-2025-while-global-spending-on-cloud-infrastructure-services-skyrockets/"
    },
    {
      "id": "ev14",
      "sourceType": "news",
      "title_en": "Google antitrust live & adverse: DOJ cross-appeal, contested data-sharing remedy; ChatGPT ~80% of AI-search",
      "title_zh": "谷歌反垄断进行且不利：司法部交叉上诉、数据共享救济被争议；ChatGPT 占 AI 搜索约 80%",
      "date": "2026-04-25",
      "stance": "oppose",
      "weightPct": 3,
      "reliability": 0.75,
      "excerpt_en": "Antitrust is a live adverse process (data-sharing remedy Google is fighting, Apple default-search deal at risk) and ChatGPT's reported ~80% AI-search share is a structural leak from the distribution moat the long-horizon GOOGL bull case leans on — closer to a base-case risk than a tail.",
      "excerpt_zh": "反垄断是正在进行的不利程序（谷歌正抗争数据共享救济、苹果默认搜索协议存疑），且 ChatGPT 据报占 AI 搜索约 80%，是对长期 GOOGL 多头所依赖的分发护城河的结构性侵蚀——更接近基准情形风险而非尾部。",
      "url": "https://www.techpolicy.press/how-ai-upended-a-historic-antitrust-case-against-google/"
    },
    {
      "id": "ev15",
      "sourceType": "news",
      "title_en": "Chinese open-weight inference cost war accelerates (GLM/DeepSeek 5-30x cheaper, MIT-licensed)",
      "title_zh": "中国开源推理成本战加速（GLM/DeepSeek 便宜 5-30 倍，MIT 许可）",
      "date": "2026-04-24",
      "stance": "mixed",
      "weightPct": 3,
      "reliability": 0.6,
      "excerpt_en": "MIT-licensed open frontier models undercut closed APIs by 5-30x — the real mid-term pressure on Gemini API pricing and a Jevons-style expansion of total inference usage, though Google's own TPUs blunt the cost disadvantage.",
      "excerpt_zh": "MIT 开源前沿模型比闭源 API 便宜 5-30 倍——这是对 Gemini API 定价的真实中期压力，也是对推理总用量的杰文斯式扩张，但谷歌自研 TPU 削弱了成本劣势。",
      "url": "https://www.abhs.in/blog/chinese-open-weights-models-4-in-12-days-glm-minimax-kimi-deepseek-cost-war-2026"
    }
  ],
  "tickers": [
    {
      "ticker": "NVDA",
      "name_en": "NVIDIA Corporation",
      "name_zh": "英伟达",
      "verdict_en": "Knee-jerk dip likely, but not a 2025-style crash — the compute thesis holds.",
      "verdict_zh": "大概率膝跳式下跌，但不是 2025 式暴跌——算力逻辑不变。",
      "horizons": [
        {
          "horizon": "short",
          "direction": "down",
          "confidence": 0.5,
          "magnitude_en": "-1% to -4% intraday",
          "magnitude_zh": "盘中 -1% 至 -4%",
          "thesis_en": "The \"cheap model = less GPU\" headline can ding NVDA today — but the market now buys these dips; the GLM/DeepSeek cadence is pre-priced, so flat-to-green is just as likely.",
          "thesis_zh": "「便宜模型=少买 GPU」的标题今天可能砸盘——但市场现在习惯买这种回调；GLM/DeepSeek 节奏已被定价，走平甚至翻红同样可能。",
          "drivers": [
            {
              "en": "DeepSeek-shock pattern-match (-17%)",
              "zh": "DeepSeek 式条件反射（-17%）"
            },
            {
              "en": "recent launches drew muted reactions",
              "zh": "近期发布反应平淡"
            },
            {
              "en": "two-sided tail",
              "zh": "双向尾部"
            }
          ],
          "evidenceIds": [
            "ev1",
            "ev7",
            "ev9",
            "ev5"
          ]
        },
        {
          "horizon": "mid",
          "direction": "neutral",
          "confidence": 0.45,
          "magnitude_en": "roughly flat, +/-8%",
          "magnitude_zh": "大致走平，±8%",
          "thesis_en": "Over 3 months capex wins: 2026 hyperscaler spend tracks $600-700B+ and the next earnings reaffirms Blackwell — but the DeepSeek recovery took ~6 months, not weeks, and a 2026 bubble overhang fattens the downside.",
          "thesis_zh": "三个月看资本开支：2026 超大厂支出 6000-7000 亿美元+，下次财报重申 Blackwell——但 DeepSeek 修复花了约 6 个月、不是几周，2026 泡沫隐忧加厚下行尾部。",
          "drivers": [
            {
              "en": "Record hyperscaler capex floor",
              "zh": "超大厂资本开支托底"
            },
            {
              "en": "next earnings is the swing",
              "zh": "下次财报是关键变量"
            },
            {
              "en": "recovery is slow + exogenous",
              "zh": "修复缓慢且靠外生催化"
            }
          ],
          "evidenceIds": [
            "ev4",
            "ev2",
            "ev6",
            "ev7",
            "ev13"
          ]
        },
        {
          "horizon": "long",
          "direction": "up",
          "confidence": 0.52,
          "magnitude_en": "modest tailwind",
          "magnitude_zh": "温和利好",
          "thesis_en": "Net bullish over a year: reasoning models burn ~100x the inference compute (Huang) and cheap open models widen who builds AI — but custom ASICs (Broadcom ~70%, TPUs 30-40% cheaper) are eating the marginal inference dollar.",
          "thesis_zh": "一年以上净偏多：推理模型烧约 100 倍推理算力（黄仁勋），廉价开源模型扩大建设者群体——但自研 ASIC（博通约 70%、TPU 便宜 30-40%）正抢走边际推理订单。",
          "drivers": [
            {
              "en": "Reasoning = more inference compute",
              "zh": "推理=更多推理算力"
            },
            {
              "en": "Jevons broadens demand",
              "zh": "杰文斯扩需"
            },
            {
              "en": "ASIC substitution is the real risk",
              "zh": "ASIC 替代是真风险"
            }
          ],
          "evidenceIds": [
            "ev3",
            "ev15",
            "ev5",
            "ev8",
            "ev6"
          ]
        }
      ]
    },
    {
      "ticker": "GOOGL",
      "name_en": "Alphabet Inc. (Google)",
      "name_zh": "谷歌母公司 Alphabet",
      "verdict_en": "At most a brief sentiment headwind — cheaper AI mostly helps a company that sells AI and owns its chips.",
      "verdict_zh": "至多是短暂情绪利空——便宜的 AI 多半帮一家卖 AI、又自有芯片的公司。",
      "horizons": [
        {
          "horizon": "short",
          "direction": "down",
          "confidence": 0.35,
          "magnitude_en": "-1% to -3%, if at all",
          "magnitude_zh": "至多 -1% 至 -3%",
          "thesis_en": "A dip is possible if the DeepSeek reflex re-fires, but it’s a coin-flip: 2026 is desensitized to Chinese launches, an open model pressures OpenAI/Anthropic more than Google, and GOOGL sits ~7% off its high.",
          "thesis_zh": "若 DeepSeek 条件反射重燃可能小跌，但接近抛硬币：2026 对中国发布已脱敏，开源模型更挤压 OpenAI/Anthropic 而非谷歌，且 GOOGL 距高点约 7%。",
          "drivers": [
            {
              "en": "AI-complex risk-off, maybe",
              "zh": "或全行业避险"
            },
            {
              "en": "2026 desensitized to Chinese launches",
              "zh": "2026 对中国发布脱敏"
            },
            {
              "en": "pressures rival APIs, not Google",
              "zh": "挤压对手 API、非谷歌"
            }
          ],
          "evidenceIds": [
            "ev9",
            "ev10",
            "ev1",
            "ev2"
          ]
        },
        {
          "horizon": "mid",
          "direction": "neutral",
          "confidence": 0.45,
          "magnitude_en": "flat to mild drag",
          "magnitude_zh": "走平至轻微拖累",
          "thesis_en": "3 months hinge on earnings, not G2M 5.2: the live risk is the capex-justification debate ($600B+ capex, AI depreciation > profits, an $84.75B June equity raise) — offset by supply-constrained Cloud and a TPU cost edge.",
          "thesis_zh": "三个月看财报，而非 G2M 5.2：真正的风险是资本开支合理性之争（开支 6000 亿+、AI 折旧超利润、6 月 847.5 亿股权融资）——但云供不应求、TPU 成本占优可对冲。",
          "drivers": [
            {
              "en": "Capex-justification scrutiny",
              "zh": "资本开支合理性受审视"
            },
            {
              "en": "Gemini API margin pressure",
              "zh": "Gemini API 利润承压"
            },
            {
              "en": "Cloud supply-constrained + TPU edge",
              "zh": "云供不应求+TPU 优势"
            }
          ],
          "evidenceIds": [
            "ev11",
            "ev15",
            "ev12",
            "ev13"
          ]
        },
        {
          "horizon": "long",
          "direction": "up",
          "confidence": 0.55,
          "magnitude_en": "net tailwind",
          "magnitude_zh": "净利好",
          "thesis_en": "Jevons favors Google over a year: cheaper intelligence explodes usage it monetizes across Search, Cloud and Workspace on its own cheap TPUs — the live risk isn’t this model, it’s antitrust and ChatGPT’s ~80% of AI-search.",
          "thesis_zh": "一年以上杰文斯利好谷歌：智能更便宜→用量暴增，谷歌靠自有廉价 TPU 在搜索/云/Workspace 变现——真正的风险不是这款模型，而是反垄断与 ChatGPT 约 80% 的 AI 搜索份额。",
          "drivers": [
            {
              "en": "Jevons across Google’s surfaces",
              "zh": "杰文斯惠及谷歌全线"
            },
            {
              "en": "TPU cost advantage",
              "zh": "TPU 成本优势"
            },
            {
              "en": "antitrust + ChatGPT search leak",
              "zh": "反垄断+ChatGPT 搜索分流"
            }
          ],
          "evidenceIds": [
            "ev2",
            "ev11",
            "ev12",
            "ev14",
            "ev8"
          ]
        }
      ]
    }
  ]
};
