// UI chrome strings + label maps for the Market Impact console. Content (the
// forecast itself) lives in the generated run data; these are the fixed labels.

import type { Direction, HorizonId, Locale, Stance } from "./types";

export const HORIZON_LABEL: Record<HorizonId, { en: string; zh: string }> = {
  short: { en: "Today", zh: "今天" },
  mid: { en: "3 months", zh: "三个月" },
  long: { en: "1+ year", zh: "一年以上" }
};

export const HORIZON_SUB: Record<HorizonId, { en: string; zh: string }> = {
  short: { en: "intraday · 1-2 sessions", zh: "盘中 · 1-2 个交易日" },
  mid: { en: "next quarter", zh: "未来一个季度" },
  long: { en: "structural", zh: "结构性趋势" }
};

export const DIRECTION_LABEL: Record<Direction, { en: string; zh: string }> = {
  up: { en: "Tailwind", zh: "利好" },
  down: { en: "Headwind", zh: "利空" },
  neutral: { en: "Neutral", zh: "中性" }
};

// Arrow glyph per direction (used in the verdict chips).
export const DIRECTION_GLYPH: Record<Direction, string> = { up: "▲", down: "▼", neutral: "▬" };

export const STANCE_LABEL: Record<Stance, { en: string; zh: string }> = {
  support: { en: "Bullish", zh: "看多" },
  oppose: { en: "Bearish", zh: "看空" },
  mixed: { en: "Mixed", zh: "中性偏" }
};

export const UI = {
  brand: { en: "Market Impact Engine", zh: "市场影响预测引擎" },
  tagline: {
    en: "Pick a catalyst. See its read-through to each stock across today, three months, and a year — decision first, evidence open.",
    zh: "选一个催化事件，看它对每只股票在「今天 / 三个月 / 一年以上」三个维度的影响——先给结论，证据全开。"
  },
  run: { en: "Run forecast", zh: "开始预测" },
  rerun: { en: "Run again", zh: "重新预测" },
  running: { en: "Forecasting…", zh: "预测中…" },
  eventLabel: { en: "Catalyst event", zh: "催化事件" },
  tickersLabel: { en: "Stocks", zh: "标的股票" },
  pipeline: { en: "Analysis pipeline", zh: "分析流程" },
  confidence: { en: "Confidence", zh: "置信度" },
  expected: { en: "Expected move", zh: "预期幅度" },
  whyHeading: { en: "Why", zh: "依据" },
  evidenceHeading: { en: "Evidence", zh: "证据" },
  evidencePool: { en: "Evidence pool", zh: "证据池" },
  reliability: { en: "Reliability", zh: "可信度" },
  weight: { en: "Weight", zh: "权重" },
  verdictHeading: { en: "Verdict", zh: "结论" },
  notAdvice: { en: "Not financial advice", zh: "非投资建议" },
  illustrative: {
    en: "Illustrative scenario analysis generated by a demo forecasting pipeline — not investment advice, not a recommendation to buy or sell.",
    zh: "由演示用预测流程生成的情景分析，仅供参考——非投资建议，不构成任何买卖推荐。"
  }
};

export function flipLocale(l: Locale): Locale {
  return l === "en" ? "zh" : "en";
}
