// Generates a SELF-CONTAINED src/styles.css = tokens.css + fonts.css + keyframes,
// so the design-sync CSS closure has no local @imports to resolve (the converter
// inlines cssEntry but doesn't follow relative @imports). tokens.css and
// fonts.css remain the editable sources; styles.css is generated. Storybook and
// app consumers import the same self-contained styles.css.
//
// Re-run after editing tokens.css or re-running fetch-fonts.mjs.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const src = join(dirname(fileURLToPath(import.meta.url)), "..", "src");
const tokens = readFileSync(join(src, "tokens.css"), "utf8").trim();
const fonts = readFileSync(join(src, "fonts.css"), "utf8").trim();

const keyframes = `@keyframes rv-spin { to { transform: rotate(360deg); } }
@keyframes rv-dots { 0%, 20% { opacity: 0.2; } 50% { opacity: 1; } 100% { opacity: 0.2; } }
@keyframes rv-rise { 0% { transform: translateY(14px); opacity: 0; } 100% { transform: translateY(0); opacity: 1; } }
@keyframes rv-glow { 0%, 100% { opacity: 0.5; transform: scale(1); } 50% { opacity: 1; transform: scale(1.3); } }
@keyframes rv-drift { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
@keyframes rv-ring-pulse { 0% { box-shadow: 0 0 0 0 var(--rv-glow); } 70% { box-shadow: 0 0 0 12px rgba(224,112,60,0); } 100% { box-shadow: 0 0 0 0 rgba(224,112,60,0); } }`;

const header = `/* GENERATED by scripts/build-css.mjs — do not edit by hand.
   Self-contained root stylesheet for the Predict Raven design system: the design
   tokens (--rv-* vars), the self-hosted @font-face blocks, and the keyframes the
   components animate with. This whole file is the CSS that rendered designs get.
   Sources: tokens.css + fonts.css (re-run this after changing either). */`;

writeFileSync(join(src, "styles.css"), `${header}\n\n${tokens}\n\n${fonts}\n\n${keyframes}\n`);
console.log("wrote self-contained src/styles.css");
