// One-shot: fetch the Google Fonts woff2 (latin subset) for the Predict Raven
// type stack and emit a local fonts.css with @font-face -> ./fonts/*.woff2, so
// the design-system styles.css @import closure resolves entirely on disk.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "..", "src");
const fontsDir = join(srcDir, "fonts");
mkdirSync(fontsDir, { recursive: true });

const URL =
  "https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap";
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const css = await (await fetch(URL, { headers: { "User-Agent": UA } })).text();

// Match each "/* subset */ @font-face {...}" pair; keep only latin.
const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g;
let m;
const out = [];
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
let count = 0;
while ((m = re.exec(css))) {
  const [, subset, block] = m;
  if (subset !== "latin") continue;
  const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
  const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1] || "400";
  const style = (block.match(/font-style:\s*(\w+)/) || [])[1] || "normal";
  const url = (block.match(/url\(([^)]+)\)\s*format\('woff2'\)/) || [])[1];
  if (!fam || !url) continue;
  const file = `${slug(fam)}-${weight}${style === "italic" ? "i" : ""}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  writeFileSync(join(fontsDir, file), buf);
  out.push(block.replace(/src:[^;]+;/, `src: url(./fonts/${file}) format('woff2');`));
  count++;
  console.log(`  ${fam} ${weight} ${style} -> fonts/${file} (${buf.length} bytes)`);
}
const header =
  "/* Generated by scripts/fetch-fonts.mjs — Google Fonts (latin), self-hosted so the\n" +
  "   styles.css @import closure resolves on disk. Re-run that script to refresh. */\n";
writeFileSync(join(srcDir, "fonts.css"), header + out.join("\n\n") + "\n");
console.log(`wrote src/fonts.css with ${count} @font-face blocks`);
